// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8kvDfOr4g5RbS0jbEUR5Mul5fCArfvgc',
    appId: '1:249686660504:web:d71a19e1ea87f0306fc7ed',
    messagingSenderId: '249686660504',
    projectId: 'evidyut-b24ca',
    authDomain: 'evidyut-b24ca.firebaseapp.com',
    storageBucket: 'evidyut-b24ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmApfBhdIaJolbyzP8Zf4YpXO6z78ZhsE',
    appId: '1:249686660504:android:209b655ea6f80f3f6fc7ed',
    messagingSenderId: '249686660504',
    projectId: 'evidyut-b24ca',
    storageBucket: 'evidyut-b24ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxjNXtwQn318D-uTNvmJml0fTEweBJxaA',
    appId: '1:249686660504:ios:d87c6b8ce9b443b66fc7ed',
    messagingSenderId: '249686660504',
    projectId: 'evidyut-b24ca',
    storageBucket: 'evidyut-b24ca.firebasestorage.app',
    iosBundleId: 'com.example.assignmentEvidyut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxjNXtwQn318D-uTNvmJml0fTEweBJxaA',
    appId: '1:249686660504:ios:d87c6b8ce9b443b66fc7ed',
    messagingSenderId: '249686660504',
    projectId: 'evidyut-b24ca',
    storageBucket: 'evidyut-b24ca.firebasestorage.app',
    iosBundleId: 'com.example.assignmentEvidyut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8kvDfOr4g5RbS0jbEUR5Mul5fCArfvgc',
    appId: '1:249686660504:web:e504424d3ecca2316fc7ed',
    messagingSenderId: '249686660504',
    projectId: 'evidyut-b24ca',
    authDomain: 'evidyut-b24ca.firebaseapp.com',
    storageBucket: 'evidyut-b24ca.firebasestorage.app',
  );
}
